export const GET_LIST_USER_REQUEST = 'GET_LIST_USER_REQUEST';
export const GET_LIST_USER_FAILURE = 'GET_LIST_USER_FAILURE';
export const GET_LIST_USER_SUCCESS = 'GET_LIST_USER_SUCCESS';

export const GET_USER_DETAIL_REQUEST = 'GET_USER_DETAIL_REQUEST';
export const GET_USER_DETAIL_FAILURE = 'GET_USER_DETAIL_FAILURE';
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';

export const GET_DROPDOWN_ROLE_REQUEST = 'GET_DROPDOWN_ROLE_REQUEST';
export const GET_DROPDOWN_ROLE_FAILURE = 'GET_DROPDOWN_ROLE_FAILURE';
export const GET_DROPDOWN_ROLE_SUCCESS = 'GET_DROPDOWN_ROLE_SUCCESS';
export const SET_DROPDOWN_ROLE = 'SET_DROPDOWN_ROLE';

export const CHANGE_PAGING = 'CHANGE_PAGING';
export const RESET_PAGING = 'RESET_PAGING';

export const ON_TOGGLE_MODAL = 'ON_TOGGLE_MODAL';

export const ON_RESET_USER_DETAIL = 'ON_RESET_USER_DETAIL';

export const ON_INIT_USER_DETAIL = 'ON_INIT_USER_DETAIL';

export const ON_CREATE_USER_REQUEST = 'ON_CREATE_USER_REQUEST';
export const ON_CREATE_USER_SUCCESS = 'ON_CREATE_USER_SUCCESS';
export const ON_CREATE_USER_FAILURE = 'ON_CREATE_USER_FAILURE';

export const ON_DELETE_USER_REQUEST = 'ON_DELETE_USER_REQUEST';
export const ON_DELETE_USER_SUCCESS = 'ON_DELETE_USER_SUCCESS';
export const ON_DELETE_USER_FAILURE = 'ON_DELETE_USER_FAILURE';

export const ON_UPDATE_USER_REQUEST = 'ON_UPDATE_USER_REQUEST';
export const ON_UPDATE_USER_SUCCESS = 'ON_UPDATE_USER_SUCCESS';
export const ON_UPDATE_USER_FAILURE = 'ON_UPDATE_USER_FAILURE';
