export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';

export const HIERACHY_SET = 'HIERACHY_SET';
export const HIERACHY_REQUEST = 'HIERACHY_REQUEST';
export const HIERACHY_SUCCESS = 'HIERACHY_SUCCESS';
export const HIERACHY_FAILURE = 'HIERACHY_FAILURE';
